### ISSUE TITLE
APK3 | Registrati -> Tasto Registrati - non è fisso in basso

### ISSUE THREAD

**Issue by fitfella** [LorenzoMazz/whereverFitness#103]
Il tasto "REGISTRATI" non è fisso in basso alla pagina come nella vecchia APK o InVision

**Comment by LorenzoMazz** [comment]
Su invision è cambiato e non è più fisso in basso, come lo mettiamo?

**Comment by fitfella** [comment]
Non avevo visto. Manteniamo allora così per ora
