### ISSUE TITLE
APK3 | Registrati -> Sesso Mancante

### ISSUE THREAD

**Issue by fitfella** [LorenzoMazz/whereverFitness#104]
Manca il campo "sesso" -> magari fare a selezione M o F (in inglese M o F)

**Comment by LorenzoMazz** [comment]
Nessun problema, sapete come deve essere visualizzato e dove metterlo con precisione?

**Comment by LorenzoMazz** [comment]
ok giriamo il quesito a Luca e chiudiamo qui
