### ISSUE TITLE
APK3 | Registrati - Campo Nazionalità Mancante - Aggiungere con lista a cascata

### ISSUE THREAD

**Issue by fitfella** [LorenzoMazz/whereverFitness#107]
Tenete in considerazione. Magari al posto della provincia mettiamo la Nazionalità? @bergo

**Comment by LorenzoMazz** [comment]
La provincia è necessaria per la ricerca di eventi vicini però giusto?

**Comment by fitfella** [comment]
in teoria non si riesce già con il CAP o la città?

**Comment by fitfella** [comment]
Confermato, aggiungerei campo Nazionalità
