### ISSUE TITLE
Obbligare a cliccare su Termini e condizioni&privacy

### ISSUE THREAD

**Issue by fitfella** [LorenzoMazz/whereverFitness#15]
Si riesce a far aprire obbligatoriamente i termini & condizioni & Privacy policy per cliccare accetto?

**Comment by LorenzoMazz** [comment]
Sì, ci sono diverse modi, come lo avevate pensato?

**Comment by fitfella** [comment]
Sentiamo lato Legal se siamo obbligati o meno. Se non lo siamo, manteniamo così !

**Comment by fitfella** [comment]
Confermo @LorenzoMazz che non siamo obbligati a farlo comparire -> Manteniamo così com'è! ;)
Unica cosa: facciamo che solo cliccando vicino alla spunta si spunta il quadratino. Cliccando vicino alla scritta invece si aprono i testi delle condizioni/privacy

**Comment by fitfella** [comment]
chiudila te una volta letto e capito ;)
