### ISSUE TITLE
Modifica Evento - Update Dettagli Dell'evento modificato

### ISSUE THREAD

**Issue by fitfella** [LorenzoMazz/whereverFitness#46]
Qual'è l'istante in cui si aggiornano i dettagli dell'evento una volta che si vuole modificare? 
quando si clicca la "ArrowBack", così da aggiornare la scheda totalmente ed in un colpo solo, giusto? Perchè se no in nel lasso di tempo che uno modifica la gente potrebbe vedere lo stesso evento in tante varianti diverse, giusto?

**Comment by LorenzoMazz** [comment]
Sì mi sembra una buona idea, stesso principio applicato al modifica profilo giusto?

**Comment by fitfella** [comment]
Esatto.

**Comment by fitfella** [comment]
Forse conviene metterci in alto a dx un "SALVA"?
