### ISSUE TITLE
APK3 | Crea Evento -> Tasto "X"

### ISSUE THREAD

**Issue by fitfella** [LorenzoMazz/whereverFitness#55]
Cliccando sul tasto "X" si dovrebbe uscire dalla creazione dell'evento, invece ti fa tornare al passo precendente( per tornare al passaggio precedente c'è la "ArrowBack"). 
Di seguito dovrebbe comparire un Popup di conferma (sottolineando che i dati saranno persi).

**Comment by riki1214** [comment]
fatto. Verificare
