### ISSUE TITLE
APK3 | Crea Evento -> Titolo -> Campo testo

### ISSUE THREAD

**Issue by fitfella** [LorenzoMazz/whereverFitness#58]
Nel campo testo del Titolo Evento 
- non c'è un limite di lunghezza -> inserirlo a max due righe
- togliere la possibilita' di andare a capo (e.g. magari sostituire "return" con "next field")

**Comment by riki1214** [comment]
Domanda: volete un limite di lunghezza (esempio 50 caratteri) o un limite di righe? Perchè non sono la stessa cosa. Se metto solo il limite di righe posso scrivere un testo lungo una pagina intera, ma vengono visualizzate solo due righe a scorrimento.

**Comment by riki1214** [comment]
Per il secondo punto invece ho messo che, dopo aver inserito il titolo, se clicchi "enter" (che non so quale sia su android), passa al field successivo e apre direttamente il calendario. Dovete verificare se funziona.

**Comment by fitfella** [comment]
Mettiamo limite di caratteri. (da definire assieme)
