### ISSUE TITLE
Limitare dimensioni dei campi di testo via n° caratteri/righe

### ISSUE THREAD

**Issue by fitfella** [LorenzoMazz/whereverFitness#65]
E' più facile limitare il n° di caratteri o il n° di righe in un campo di testo? 
Penso che il meglio sia limitare il n° di caratteri per avere sempre dimensioni simili dei campi di testo su diversi dispositivi. Giusto?

**Comment by LorenzoMazz** [comment]
è possibile limitare entrambi. Se limitare uno o l'altro dipende dai casi. Lo aggiungo alle cose da spiegare a voce. Quando leggete chiudete pure
