### ISSUE TITLE
APK3 | Crea Evento -> N° max Fitfellas - "Next Field"

### ISSUE THREAD

**Issue by fitfella** [LorenzoMazz/whereverFitness#67]
Cliccando sul bottone "next field" della tastiera non si passa al campo "Descrizione Evento"

**Comment by riki1214** [comment]
Ho capito che se sono nel campo inserisci numero max e clicco su "enter" della tastiera android mi porta automaticamente nel campo descrizione, giusto? Per ora ho fatto questo. Se ho capito male scrivete qui sotto che correggo.
