### ISSUE TITLE
APK3 | Crea Evento -> Eventi Femminili&Ripetizione Evento (update)

### ISSUE THREAD

**Issue by fitfella** [LorenzoMazz/whereverFitness#71]
Le funzionalità RIPETIZIONE EVENTO & EVENTO FEMMINILE va benissimo ma è una funzionalità nella versione Alfa -> toglierla (i.e. tenetevi il codice ma non inseritela in nella release alfa-> saltare questo passaggio nella crezione

**Comment by riki1214** [comment]
fatto. Verificare
