### ISSUE TITLE
APK3 | Scheda Evento -> Manca Visualizzazione evento a cui sono già iscritto

### ISSUE THREAD

**Issue by fitfella** [LorenzoMazz/whereverFitness#90]
Manca una scheda di un evento a cui sono già iscritto. 
Dovrebbe cambiare solamente il pulsante in basso che diventa "ABBANDONA EVENTO" in stile scritta rossa(e.g. "ELIMINA ACCOUNT" in Profilo)

**Comment by LorenzoMazz** [comment]
Con l'implementazione delle API mettiamo a disposizione tutti i tipi. Visto che è il prossimo passaggio da fare non lo inseriamo nella versione demo
